document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'UTF-8\'>");
document.writeln("		<title></title>");

document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<!--主页底部开始-->");
document.writeln("			<div class=\'footer\'>");
document.writeln("				<div class=\'container\'>");
document.writeln("					<div class=\'row\'>");
document.writeln("						<div class=\'yhq_help fh5co-project col-md-6 col-md-offset-2 wow fadeInUp\'>");
document.writeln("							<p>联系我们</p>");
document.writeln("							<p>地址：北京市朝阳区望京东路4号恒基伟业大厦B1座6层628号</p>");
document.writeln("							<p>电话：010-52806389/010-59797564</p>");
document.writeln("						</div>");
document.writeln("");
document.writeln("						<div class=\'yhqwm fh5co-project col-md-2 wow fadeInUp\' data-wow-delay=\'.2s\'>");
document.writeln("							<img src=\'img/homeImg/yhq_wxgzh.png\' alt=\'云海桥二维码\' />");
document.writeln("							<p>关注云海桥</p>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("");
document.writeln("			</div>");
document.writeln("			<div class=\'clear\'></div>");
document.writeln("");
document.writeln("			<div class=\'footer2\'>");
document.writeln("				<div class=\'container\'>");
document.writeln("					<div class=\'row\'>");
document.writeln("						<div class=\'col-md-12 text-center\'>");
document.writeln("							<p>Copyright © 2013 本站网络实名/通用网址：\'云海慧服（北京）技术有限公司\'</p>");
document.writeln("						</div>");
document.writeln("");
document.writeln("					</div>");
document.writeln("");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("					<div class=\'wqd-help\'>");
document.writeln("			<div class=\'wqd-help-box\'>");
document.writeln("				<div class=\'wqd-help-icon\'>");
document.writeln("					<div class=\'animated-circles js-animated-circles\'>");
document.writeln("						<div class=\'circle c-1\'></div>");
document.writeln("						<div class=\'circle c-2\'></div>");
document.writeln("						<div class=\'circle c-3\'></div>");
document.writeln("					</div>");
document.writeln("					<div class=\'wqd-kficon\'>");
document.writeln("						<i class=\'iconfont  icon-xinxi\'></i>");
document.writeln("						<!--<img src=\'img/homeImg/wqd-help.png\' alt=\'\'>-->");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'wqd-information-box\'>");
document.writeln("					<div class=\'wqd-information\'>");
document.writeln("						<a href=\'###\' target=\'_blank\'>");
document.writeln("							<img style=\'width:290px;height:140px\' src=\'img/homeImg/helptop.jpg\' alt=\'\'>");
document.writeln("						</a>");
document.writeln("						");
document.writeln(" 			<div class=\'help-phone\'>");
document.writeln(" 				<h4>客服电话</h4>");
document.writeln(" 				<p>010-52806389</p>");
document.writeln(" 				<p>010-59797564</p>");
document.writeln("                   ");
document.writeln("                     	");
document.writeln("                </div>");
document.writeln("						<div class=\'help-url\'>");
document.writeln("							<img src=\'img/homeImg/yhq_wxgzh.png\' alt=\'云海桥二维码\'>");
document.writeln("							<p class=\'help-url-p\'>扫描关注微信公众号</p>");
document.writeln("							<p>周一至周五 9:00~18:00</p>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'wqd-goTop\' onclick=\'$(&#39;body,html&#39;).animate({scrollTop:0},500);\'>");
document.writeln("					<i class=\'iconfont  icon-up\'></i>");
document.writeln("					<div class=\'goTop-title\'>");
document.writeln("						返回顶部");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("			<!--主页底部结束-->");
document.writeln("					");
document.writeln("	</body>");
document.writeln("</html>");
document.writeln("");