document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("");
document.writeln("	<head>");
document.writeln("		<meta charset=\'UTF-8\'>");
document.writeln("		<title></title>	");
document.writeln("		<link rel=\'stylesheet\' href=\'css/iconfont.css\' />");
document.writeln("	<script>");
document.writeln("	var _hmt = _hmt || [];");
document.writeln("(function() {");
document.writeln("  var hm = document.createElement(\'script\');");
document.writeln("  hm.src = \'https://hm.baidu.com/hm.js?3eefb55e3b18f6649674e452413a32f5\';");
document.writeln("  var s = document.getElementsByTagName(\'script\')[0]; ");
document.writeln("  s.parentNode.insertBefore(hm, s);");
document.writeln("})();");
document.writeln("");
document.writeln("		</script>");
document.writeln("	");
document.writeln("	</head>");
document.writeln("");
document.writeln("	<body>");
document.writeln("		<div class=\'fh5co-loader\'></div>");
document.writeln("		<div id=\'yhq_header\' class=\'mini\'>");
document.writeln("			<div class=\'container\'>");
document.writeln("				<div class=\'row\'>");
document.writeln("					<div id=\'yhq_Login\' class=\'col-xs-4\'>");
document.writeln("						<a href=\'index.html\'><img  src=\'img/homeImg/im_logo@1.5x.png\' alt=\'云海桥\' /></a>");
document.writeln("					</div>");
document.writeln("					<div class=\'col-xs-8 text-right menu-1\'>");
document.writeln("						<ul class=\'yhq_nav\'>");
document.writeln("							<li class=\'navitem\'>");
document.writeln("								<a  class=\'active\' href=\'index.html\'><span data-hover=\'首页\'>首页</span></a>");
document.writeln("							</li>");
document.writeln("							<li class=\'navitem has-dropdown\'>");
document.writeln("								<a href=\'###\'><span data-hover=\'关于我们\'>关于我们</span><i class=\'iconfont icon-xiangxia\'></i></a>");
document.writeln("");
document.writeln("								<ul class=\'subnav\'>");
document.writeln("									<li>");
document.writeln("										<a href=\'about.html\'>公司简介</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'News.html\'>新闻动态</a>");
document.writeln("									</li>");
document.writeln("								</ul>");
document.writeln("							</li>");
document.writeln("							<li class=\'navitem\'>");
document.writeln("								<a href=\'solution.html\'><span data-hover=\'解决方案\'>解决方案</span></a>");
document.writeln("							</li>");
document.writeln("							<li class=\'navitem has-dropdown\'>");
document.writeln("								<a href=\'###\'><span data-hover=\'定制服务\'>定制服务</span><i class=\'iconfont  icon-xiangxia\'></i></a>");
document.writeln("								<ul class=\'subnav dropdown\'>");
document.writeln("									<li>");
document.writeln("										<a href=\'polyC.html\'>聚库云</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'WarningC.html\'>预警云</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'matchC.html\'>速配云</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'antonC.html\'>安盾云</a>");
document.writeln("									</li>");
document.writeln("								</ul>");
document.writeln("							</li>");
document.writeln("							<li class=\'navitem\'>");
document.writeln("								<a href=\'Operating.html\'><span data-hover=\'运营传播\'>运营传播</span></a>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("");
document.writeln("		</div>");
document.writeln("		");
document.writeln("	</body>");
document.writeln("</html>");
document.writeln("");